### ISSUE TITLE
Uncaught Error: Cannot find module 'cson'

### ISSUE THREAD

**Issue by Qdafengzi** [Reedo0910/atom-simplified-chinese-menu#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [atom-simplified-chinese-menu](https://github.com/Reedo0910/atom-simplified-chinese-menu) package 0.5.11

### Stack Trace

Uncaught Error: Cannot find module 'cson'

```
At module.js:457

Error: Cannot find module 'cson'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at delay (/packages/atom-simplified-chinese-menu/lib/main.coffee:8:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-simplified-chinese-menu 0.5.11 
```

**Comment by Reedo0910** [comment]
我暂时重现不了这个问题。
刚刚发布了`0.5.12`，升级了一下`cson`的版本，你看看有没有修复。

**Comment by TIL-MICE** [comment]
Settings
Uncaught Error: Cannot find module 'cson'
module.js:457
Hide Stack Trace
Error: Cannot find module 'cson'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at delay (/home/lckiss/.atom/packages/atom-simplified-chinese-menu-0.6.5/lib/main.coffee:8:12)
The error was thrown from the atom-simplified-chinese-menu package. This issue has already been reported.
View Issue


最新的zip版 elementary os 16.04

**Comment by mangococo** [comment]
似乎mac就会出现这个问题？？

**Comment by cngege** [comment]
遇到了错误 [Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.0 ia32
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [atom-simplified-chinese-menu](https://github.com/Reedo0910/atom-simplified-chinese-menu) package 0.6.5


### Stack Trace

Uncaught Error: Cannot find module 'cson'

```
At module.js:545

Error: Cannot find module 'cson'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.38.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.38.0/resources/app/static/<embedded>:11:155156)
    at Module.require (/app.asar/static/index.js:53:43)
    at require (~/AppData/Local/atom/app-1.38.0/resources/app/static/<embedded>:11:146462)
    at delay (/packages/chinese/lib/main.coffee:8:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-simplified-chinese-menu 0.6.5 
atom-simplified-chinese-menu 0.6.5 
```
